# Datos de Tráfico en Madrid
### -Descargaremos los datos disponibles para los años 2018 y 2019
### -Descartaremos los datos no relevantes para medir la intensidad de trafico de las calles de la ciudad de Madrid. 
### -Agruparemos los datos a medianas por dia
### -Sacaremos un csv resultado a mergear con las otras ramas (meteo y calidad del aire)
### -eliminaremos los archivos utilizados en el proceso para que estos no suban al repositorio (por eficiencia y limitacion 500mb github)

In [2]:
#importamos librerías
import pandas as pd
import requests as requests
import datetime
import os

In [2]:
# definimos variables para cada zip que necesitamos cada url https://datos.madrid.es/portal/site/egob/menuitem.c05c1f754a33a9fbe4b2e4b284f1a5a0/?vgnextoid=33cb30c367e78410VgnVCM1000000b205a0aRCRD&vgnextchannel=374512b9ace9f310VgnVCM100000171f5a0aRCRD&vgnextfmt=default

datos_trafico_1801="https://datos.madrid.es/egob/catalogo/208627-56-transporte-ptomedida-historico.zip"
datos_trafico_1802="https://datos.madrid.es/egob/catalogo/208627-57-transporte-ptomedida-historico.zip"
datos_trafico_1803="https://datos.madrid.es/egob/catalogo/208627-58-transporte-ptomedida-historico.zip"
datos_trafico_1804="https://datos.madrid.es/egob/catalogo/208627-59-transporte-ptomedida-historico.zip"
datos_trafico_1805="https://datos.madrid.es/egob/catalogo/208627-60-transporte-ptomedida-historico.zip"
datos_trafico_1806="https://datos.madrid.es/egob/catalogo/208627-61-transporte-ptomedida-historico.zip"
datos_trafico_1807="https://datos.madrid.es/egob/catalogo/208627-62-transporte-ptomedida-historico.zip"
datos_trafico_1808="https://datos.madrid.es/egob/catalogo/208627-63-transporte-ptomedida-historico.zip"
datos_trafico_1809="https://datos.madrid.es/egob/catalogo/208627-64-transporte-ptomedida-historico.zip"
datos_trafico_1810="https://datos.madrid.es/egob/catalogo/208627-65-transporte-ptomedida-historico.zip"
datos_trafico_1811="https://datos.madrid.es/egob/catalogo/208627-66-transporte-ptomedida-historico.zip"
datos_trafico_1812="https://datos.madrid.es/egob/catalogo/208627-67-transporte-ptomedida-historico.zip"
datos_trafico_1901="https://datos.madrid.es/egob/catalogo/208627-68-transporte-ptomedida-historico.zip"
datos_trafico_1902="https://datos.madrid.es/egob/catalogo/208627-69-transporte-ptomedida-historico.zip"
datos_trafico_1903="https://datos.madrid.es/egob/catalogo/208627-70-transporte-ptomedida-historico.zip"
datos_trafico_1904="https://datos.madrid.es/egob/catalogo/208627-71-transporte-ptomedida-historico.zip"
datos_trafico_1905="https://datos.madrid.es/egob/catalogo/208627-72-transporte-ptomedida-historico.zip"
datos_trafico_1906="https://datos.madrid.es/egob/catalogo/208627-73-transporte-ptomedida-historico.zip"
datos_trafico_1907="https://datos.madrid.es/egob/catalogo/208627-74-transporte-ptomedida-historico.zip"
datos_trafico_1908="https://datos.madrid.es/egob/catalogo/208627-75-transporte-ptomedida-historico.zip"
datos_trafico_1909="https://datos.madrid.es/egob/catalogo/208627-76-transporte-ptomedida-historico.zip"
datos_trafico_1910="https://datos.madrid.es/egob/catalogo/208627-77-transporte-ptomedida-historico.zip"
datos_trafico_1911="https://datos.madrid.es/egob/catalogo/208627-78-transporte-ptomedida-historico.zip"
datos_trafico_1912="https://datos.madrid.es/egob/catalogo/208627-79-transporte-ptomedida-historico.zip"
Estrucutra_ficheros_csv="https://datos.madrid.es/FWProjects/egob/Catalogo/Transporte/Trafico/ficheros/Estructura_DS_Contenido_Trafico_Historico.pdf"

#utilizamos la libreria requests para descargar cada zip. Urllib da error 403 y 302 mientras que con la libreria requests estos errores se resuelven
#Tener en cuenta que cada zip pesa unos 80mb y hay 24. Pues necesita descargarse unos 2gb
#Una vez recorridos los archivos , agrupados por dia y concatenados en un dataframe debemos eliminarlos, ya que no subiran al repositorio github donde tenemos limitacion de 500mb. para ello utilizaremos remove

response = requests.get(datos_trafico_1801, allow_redirects=True) 
file = open('datos_trafico_1801.zip', 'wb').write(response.content)

response = requests.get(datos_trafico_1802, allow_redirects=True) 
file = open('datos_trafico_1802.zip', 'wb').write(response.content)

response = requests.get(datos_trafico_1803, allow_redirects=True) 
file = open('datos_trafico_1803.zip', 'wb').write(response.content)

response = requests.get(datos_trafico_1804, allow_redirects=True) 
file = open('datos_trafico_1804.zip', 'wb').write(response.content)

response = requests.get(datos_trafico_1805, allow_redirects=True) 
file = open('datos_trafico_1805.zip', 'wb').write(response.content)

response = requests.get(datos_trafico_1806, allow_redirects=True) 
file = open('datos_trafico_1806.zip', 'wb').write(response.content)

response = requests.get(datos_trafico_1807, allow_redirects=True) 
file = open('datos_trafico_1807.zip', 'wb').write(response.content)

response = requests.get(datos_trafico_1808, allow_redirects=True) 
file = open('datos_trafico_1808.zip', 'wb').write(response.content)

response = requests.get(datos_trafico_1809, allow_redirects=True) 
file = open('datos_trafico_1809.zip', 'wb').write(response.content)

response = requests.get(datos_trafico_1810, allow_redirects=True) 
file = open('datos_trafico_1810.zip', 'wb').write(response.content)

response = requests.get(datos_trafico_1811, allow_redirects=True) 
file = open('datos_trafico_1811.zip', 'wb').write(response.content)

response = requests.get(datos_trafico_1812, allow_redirects=True) 
file = open('datos_trafico_1812.zip', 'wb').write(response.content)


response = requests.get(datos_trafico_1901, allow_redirects=True) 
file = open('datos_trafico_1901.zip', 'wb').write(response.content)

response = requests.get(datos_trafico_1902, allow_redirects=True) 
file = open('datos_trafico_1902.zip', 'wb').write(response.content)

response = requests.get(datos_trafico_1903, allow_redirects=True) 
file = open('datos_trafico_1903.zip', 'wb').write(response.content)

response = requests.get(datos_trafico_1904, allow_redirects=True) 
file = open('datos_trafico_1904.zip', 'wb').write(response.content)

response = requests.get(datos_trafico_1905, allow_redirects=True) 
file = open('datos_trafico_1905.zip', 'wb').write(response.content)

response = requests.get(datos_trafico_1906, allow_redirects=True) 
file = open('datos_trafico_1906.zip', 'wb').write(response.content)

response = requests.get(datos_trafico_1907, allow_redirects=True) 
file = open('datos_trafico_1907.zip', 'wb').write(response.content)

response = requests.get(datos_trafico_1908, allow_redirects=True) 
file = open('datos_trafico_1908.zip', 'wb').write(response.content)

response = requests.get(datos_trafico_1909, allow_redirects=True) 
file = open('datos_trafico_1909.zip', 'wb').write(response.content)

response = requests.get(datos_trafico_1910, allow_redirects=True) 
file = open('datos_trafico_1910.zip', 'wb').write(response.content)

response = requests.get(datos_trafico_1911, allow_redirects=True) 
file = open('datos_trafico_1911.zip', 'wb').write(response.content)

response = requests.get(datos_trafico_1912, allow_redirects=True) 
file = open('datos_trafico_1912.zip', 'wb').write(response.content)


response = requests.get(Estrucutra_ficheros_csv, allow_redirects=True) 
file = open('Estructura_DS_Contenido_Trafico_Historico.pdf', 'wb').write(response.content)

    Mientras descargamos todos los datos podemos entender su contenido de la documentacion

## Contenido CSV
#### Los diversos sistemas de control de tráfico de la ciudad de Madrid proporcionan periódicamente y de forma automática datos de todos los detectores de vehículos de los puntos de medida que controlan. La base de datos SICTRAM los registra e integra sobre periodos de 15 minutos.
#### Si el sensor no proporciona información de una de las muestras del periodo, no se contabilizará esa información; no obstante, si el sensor proporciona información pero los parámetros de calidad de la misma no son óptimos la información se integra, pero se reporta como posible error. El error puede deberse porque el sensor detecta parámetros fuera de los rangos establecidos o porque alguno de los sensores que componen el punto de medida no esté operativo (por ejemplo, en un punto de medida de 4 carriles uno de los carriles no está funcionando).
#### Los históricos de Puntos de Medida se exportan en un archivo CSV con los siguientes campos:
#### Nombre / Tipo / Descripción
    * idelem / Entero / Identificación única del Punto de Medida en los sistemas de control del tráfico del Ayuntamiento de Madrid.
    
    * fecha / Fecha / Fecha y hora oficiales de Madrid con formato yyyy-mm-dd hh:mi:ss
    
    * identif / Texto / Identificador del Punto de Medida en los Sistemas de Tráfico (se proporciona por compatibilidad hacia atrás).
    
    * tipo_elem / Texto / Nombre del Tipo de Punto de Medida: Urbano o M30.
    
    * Intensidad / Entero /Intensidad del Punto de Medida en el periodo de 15 minutos (vehículos/hora). Un valor negativo implica la ausencia de datos.
    
    * ocupacion / Entero / Tiempo de Ocupación del Punto de Medida en el periodo de 15 minutos (%). Un valor negativo implica la ausencia de datos.
    
    * carga / Entero / Carga de vehículos en el periodo de 15 minutos. Parámetro que tiene en cuenta intensidad, ocupación y capacidad de la vía y establece el grado de uso de la vía de 0 a 100. Un valor negativo implica la ausencia de datos.
    
    *vmed / Entero / Velocidad media de los vehículos en el periodo de 15 minutos (Km./h). Sólo para puntos de medida interurbanos M30. Un valor negativo implica la ausencia de datos.
    
    * error / Texto / Indicación de si ha habido al menos una muestra errónea o sustituida en el periodo de 15 minutos.
        N: no ha habido errores ni sustituciones
        E: los parámetros de calidad de alguna de las muestras integradas no son óptimos.
        S: alguna de las muestras recibidas era totalmente errónea y no se ha integrado.
        
    * periodo_integracion / Entero / Número de muestras recibidas y consideradas para el periodo de integración.

In [44]:
#carga de datos de trafico en pandas. Empezamos con uno de ellos para decidir como trataremos los datos
trafico_1801 = pd.read_csv('datos_trafico_1801.zip', compression='zip', header=0, sep=';', quotechar='"')

In [45]:
#visualizamos uno de los dataframes
trafico_1801.head()

,id,fecha,tipo_elem,intensidad,ocupacion,carga,vmed,error,periodo_integracion
0,1001,2018-01-01 00:00:00,PUNTOS MEDIDA M-30,204,12,0,73,N,5
1,1002,2018-01-01 00:00:00,PUNTOS MEDIDA M-30,252,1,0,79,N,5
2,1003,2018-01-01 00:00:00,PUNTOS MEDIDA M-30,420,2,0,82,N,5
3,1006,2018-01-01 00:00:00,PUNTOS MEDIDA M-30,288,1,0,75,N,5
4,1009,2018-01-01 00:00:00,PUNTOS MEDIDA M-30,276,0,0,76,N,5

In [46]:
#nos interesan solo los registros de los elementos de medida relacionados con la ciudad de madrid, no los de carreteras de madrid.
#tampoco queremos datos erroneos
#por ello nos quedaremos solo con los elementos tipo "URB" y error "N"
trafico_1801['tipo_elem'].value_counts(ascending=False)

PUNTOS MEDIDA URBANOS    10339086
PUNTOS MEDIDA M-30        1212028
Name: tipo_elem, dtype: int64

In [47]:
trafico_1801 = trafico_1801.loc[trafico_1801.tipo_elem.str.contains('URB')]
trafico_1801 = trafico_1801.loc[trafico_1801.error =='N']
trafico_1801.head()

,id,fecha,tipo_elem,intensidad,ocupacion,carga,vmed,error,periodo_integracion
47,3395,2018-01-01 00:00:00,PUNTOS MEDIDA URBANOS,65,0,2,0,N,9
48,3396,2018-01-01 00:00:00,PUNTOS MEDIDA URBANOS,60,0,2,0,N,3
49,3397,2018-01-01 00:00:00,PUNTOS MEDIDA URBANOS,107,0,5,0,N,15
50,3398,2018-01-01 00:00:00,PUNTOS MEDIDA URBANOS,59,1,2,0,N,15
51,3399,2018-01-01 00:00:00,PUNTOS MEDIDA URBANOS,48,1,4,0,N,8

In [48]:
trafico_1801.shape

(10339086, 9)

In [49]:
##descartamos las columnas que no utilizaremos y nos quedamos con fecha,intensidad,ocupacion y carga
trafico_1801=trafico_1801.drop(columns=['tipo_elem','vmed','error','periodo_integracion','id'])
trafico_1801.head()

                  fecha  intensidad  ocupacion  carga
47  2018-01-01 00:00:00          65          0      2
48  2018-01-01 00:00:00          60          0      2
49  2018-01-01 00:00:00         107          0      5
50  2018-01-01 00:00:00          59          1      2
51  2018-01-01 00:00:00          48          1      4

In [50]:
trafico_1801.dtypes

fecha         object
intensidad     int64
ocupacion      int64
carga          int64
dtype: object

In [51]:
#antes de agrupar por campo fecha hay que convertirla en fecha tipo yyyy-mm-dd
trafico_1801["fecha"]=pd.to_datetime(trafico_1801["fecha"], format='%Y-%m-%d', errors='coerce')
trafico_1801['fecha'] = pd.DatetimeIndex(trafico_1801['fecha']).date
trafico_1801.head()

         fecha  intensidad  ocupacion  carga
47  2018-01-01          65          0      2
48  2018-01-01          60          0      2
49  2018-01-01         107          0      5
50  2018-01-01          59          1      2
51  2018-01-01          48          1      4

In [52]:
## en la documentacion comentan que en ausencia de datos vendran un valor negativo, concretamente -1. pero no me encuentra estos valores con pandas. hay que ver como tratarlos
trafico_1801.isin(['-1']).sum(axis=0)

fecha         0
intensidad    0
ocupacion     0
carga         0
dtype: int64

In [53]:
# agruparemos cada valor de las todas las estaciones medida a 1 valor mediana por fecha, asi calculamos valores por fecha para la ciudad de madrid
trafico_intensidad= trafico_1801.groupby('fecha')['intensidad'].median()
trafico_ocupacion= trafico_1801.groupby('fecha')['ocupacion'].median()
trafico_carga= trafico_1801.groupby('fecha')['carga'].median()

trafico_intensidad = pd.merge(trafico_intensidad, trafico_ocupacion,left_index=True, right_index=True)
trafico_1801 = pd.merge(trafico_intensidad, trafico_carga,left_index=True, right_index=True)
trafico_1801.reset_index(level=0, inplace=True)
trafico_1801.shape

(31, 4)

In [55]:
# antes de concatenear tenemos que hacer el mismo tratamiento de datos 23 veces mas, 1 por cada resto de meses, ya que por falta de memoria no podemos concatenar los datos antes de agruparlos por fechas
# agregaremos todos los pasos en una funcion para facilitarlo 

def tratamiento_datos_csv_trafico_madrid(actuality):
    #cargar el zip a un df
    trafico = pd.read_csv('datos_trafico_'+str(actuality)+'.zip', compression='zip', header=0, sep=';', quotechar='"')
    #seleccionar solo los datos tipo urbanos sin errores
    trafico = trafico.loc[trafico.tipo_elem.str.contains('URB')]
    trafico = trafico.loc[trafico.error =='N']
    #hacer drop a las columnas inecesarias
    trafico=trafico.drop(columns=['tipo_elem','vmed','error','periodo_integracion','id'])
    #convertir la fechahora a fecha
    trafico["fecha"]=pd.to_datetime(trafico["fecha"], format='%Y-%m-%d', errors='coerce')
    trafico['fecha']=pd.DatetimeIndex(trafico['fecha']).date
    #agrupar valores a mediana por cada fecha para conseguir 1 valor/dia.
    trafico_intensidad= trafico.groupby('fecha')['intensidad'].median()
    trafico_ocupacion= trafico.groupby('fecha')['ocupacion'].median()
    trafico_carga= trafico.groupby('fecha')['carga'].median()
    trafico_intensidad = pd.merge(trafico_intensidad, trafico_ocupacion,left_index=True, right_index=True)
    trafico= pd.merge(trafico_intensidad, trafico_carga,left_index=True, right_index=True)
    trafico.reset_index(level=0, inplace=True)
    return trafico

In [56]:
#ejecutamos la funcion para cada actuality y guardamos su resultado en una variable que contendra el dataframe a concatenar.
# va a tardar un poco ademas de consumir recursos.

trafico_1801=tratamiento_datos_csv_trafico_madrid(1801)
trafico_1802=tratamiento_datos_csv_trafico_madrid(1802)
trafico_1803=tratamiento_datos_csv_trafico_madrid(1803)
trafico_1804=tratamiento_datos_csv_trafico_madrid(1804)
trafico_1805=tratamiento_datos_csv_trafico_madrid(1805)
trafico_1806=tratamiento_datos_csv_trafico_madrid(1806)
trafico_1807=tratamiento_datos_csv_trafico_madrid(1807)
trafico_1808=tratamiento_datos_csv_trafico_madrid(1808)
trafico_1809=tratamiento_datos_csv_trafico_madrid(1809)
trafico_1810=tratamiento_datos_csv_trafico_madrid(1810)
trafico_1811=tratamiento_datos_csv_trafico_madrid(1811)
trafico_1812=tratamiento_datos_csv_trafico_madrid(1812)

trafico_1901=tratamiento_datos_csv_trafico_madrid(1901)
trafico_1902=tratamiento_datos_csv_trafico_madrid(1902)
trafico_1903=tratamiento_datos_csv_trafico_madrid(1903)
trafico_1904=tratamiento_datos_csv_trafico_madrid(1904)
trafico_1905=tratamiento_datos_csv_trafico_madrid(1905)
trafico_1906=tratamiento_datos_csv_trafico_madrid(1906)
trafico_1907=tratamiento_datos_csv_trafico_madrid(1907)
trafico_1908=tratamiento_datos_csv_trafico_madrid(1908)
trafico_1909=tratamiento_datos_csv_trafico_madrid(1909)
trafico_1910=tratamiento_datos_csv_trafico_madrid(1910)
trafico_1911=tratamiento_datos_csv_trafico_madrid(1911)
trafico_1912=tratamiento_datos_csv_trafico_madrid(1912)

In [57]:
#concatenamos los 24 dataframes en 1
trafico_mad=pd.concat([
trafico_1801,
trafico_1802,
trafico_1803,
trafico_1804,
trafico_1805,
trafico_1806,
trafico_1807,
trafico_1808,
trafico_1809,
trafico_1810,
trafico_1811,
trafico_1812,
trafico_1901,
trafico_1902,
trafico_1903,
trafico_1904,
trafico_1905,
trafico_1906,
trafico_1907,
trafico_1908,
trafico_1909,
trafico_1910,
trafico_1911,
trafico_1912,
])

In [58]:
trafico_mad.shape

(730, 4)

In [61]:
trafico_mad.describe()

       intensidad   ocupacion       carga
count  730.000000  730.000000  730.000000
mean   185.502740    3.073973   15.135616
std     35.789134    1.077266    3.606421
min     90.000000    1.000000    6.000000
25%    153.000000    2.000000   12.000000
50%    199.000000    3.000000   17.000000
75%    213.000000    4.000000   18.000000
max    253.000000    6.000000   21.000000

In [62]:
#exportaremos los datos trafico_mad a csv:
trafico_mad.to_csv('trafico_mad.csv', index=False)

In [63]:
# una vez todo procesado no necesitamos los zip originales
os.remove("datos_trafico_1801.zip")
os.remove("datos_trafico_1802.zip")
os.remove("datos_trafico_1803.zip")
os.remove("datos_trafico_1804.zip")
os.remove("datos_trafico_1805.zip")
os.remove("datos_trafico_1806.zip")
os.remove("datos_trafico_1807.zip")
os.remove("datos_trafico_1808.zip")
os.remove("datos_trafico_1809.zip")
os.remove("datos_trafico_1810.zip")
os.remove("datos_trafico_1811.zip")
os.remove("datos_trafico_1812.zip")
os.remove("datos_trafico_1901.zip")
os.remove("datos_trafico_1902.zip")
os.remove("datos_trafico_1903.zip")
os.remove("datos_trafico_1904.zip")
os.remove("datos_trafico_1905.zip")
os.remove("datos_trafico_1906.zip")
os.remove("datos_trafico_1907.zip")
os.remove("datos_trafico_1908.zip")
os.remove("datos_trafico_1909.zip")
os.remove("datos_trafico_1910.zip")
os.remove("datos_trafico_1911.zip")
os.remove("datos_trafico_1912.zip")